### ISSUE TITLE
Clarify purpose

### ISSUE THREAD

**Issue by pmackay** [openblockchains/universum#1]
I've read the docs for the this project and would like to ask if this doc could clarify, is the purpose of this project to experiment with programming contracts, but not actually to build contracts? Is there any intent to do something like Vyper and support compiling to the Ethereum ABI?

**Comment by geraldb** [comment]
Thanks for your interest in Universum. Please post general question to the forum / mailing list <https://github.com/s6ruby/universum#questions-comments>  Thanks. Greetings from Vienna.  PS: See the "Red Paper" for the "vision" incl. in the future vyper-like ethereum support with "cross-compilation" <https://github.com/s6ruby/redpaper>.
